spring:
  application:
    name: tradukisto
  ai:
    openai:
      base-url: http://localhost:8080
      api-key: hogehoge
      chat:
        options:
          model: plamo2-translate
          temperature: 0
server:
  port: 8081
