openapi: 3.0.4
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

paths:
  /api/v1/translate:
    $ref: "./paths/translate/translate.yaml#/paths/~1api~1v1~1translate"
  /api/v1/translate/stream:
    $ref: "./paths/translate/translate-stream.yaml#/paths/~1api~1v1~1translate~1stream"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
